export const FACE_ANALYSIS_REQUEST = 'FACE_ANALYSIS_REQUEST';
export const FACE_ANALYSIS_SUCCESS = 'FACE_ANALYSIS_SUCCESS';
export const FACE_ANALYSIS_FAIL = 'FACE_ANALYSIS_FAIL';
export const FACE_ANALYSIS_RESET = 'FACE_ANALYSIS_RESET';

export const GET_RECOMMENDATIONS_REQUEST = 'GET_RECOMMENDATIONS_REQUEST';
export const GET_RECOMMENDATIONS_SUCCESS = 'GET_RECOMMENDATIONS_SUCCESS';
export const GET_RECOMMENDATIONS_FAIL = 'GET_RECOMMENDATIONS_FAIL';
