export const QUIZ_SUBMIT_REQUEST = "QUIZ_SUBMIT_REQUEST";
export const QUIZ_SUBMIT_SUCCESS = "QUIZ_SUBMIT_SUCCESS";
export const QUIZ_SUBMIT_FAIL = "QUIZ_SUBMIT_FAIL";

export const QUIZ_GET_RESPONSE_REQUEST = "QUIZ_GET_RESPONSE_REQUEST";
export const QUIZ_GET_RESPONSE_SUCCESS = "QUIZ_GET_RESPONSE_SUCCESS";
export const QUIZ_GET_RESPONSE_FAIL = "QUIZ_GET_RESPONSE_FAIL";

export const QUIZ_GET_STATS_REQUEST = "QUIZ_GET_STATS_REQUEST";
export const QUIZ_GET_STATS_SUCCESS = "QUIZ_GET_STATS_SUCCESS";
export const QUIZ_GET_STATS_FAIL = "QUIZ_GET_STATS_FAIL";
