export const SKINCARE_TIP_LIST_REQUEST = "SKINCARE_TIP_LIST_REQUEST";
export const SKINCARE_TIP_LIST_SUCCESS = "SKINCARE_TIP_LIST_SUCCESS";
export const SKINCARE_TIP_LIST_FAIL = "SKINCARE_TIP_LIST_FAIL";

export const SKINCARE_TIP_DETAILS_REQUEST = "SKINCARE_TIP_DETAILS_REQUEST";
export const SKINCARE_TIP_DETAILS_SUCCESS = "SKINCARE_TIP_DETAILS_SUCCESS";
export const SKINCARE_TIP_DETAILS_FAIL = "SKINCARE_TIP_DETAILS_FAIL";

export const SKINCARE_TIP_LIKE_REQUEST = "SKINCARE_TIP_LIKE_REQUEST";
export const SKINCARE_TIP_LIKE_SUCCESS = "SKINCARE_TIP_LIKE_SUCCESS";
export const SKINCARE_TIP_LIKE_FAIL = "SKINCARE_TIP_LIKE_FAIL";

export const SKINCARE_TIP_CATEGORIES_REQUEST = "SKINCARE_TIP_CATEGORIES_REQUEST";
export const SKINCARE_TIP_CATEGORIES_SUCCESS = "SKINCARE_TIP_CATEGORIES_SUCCESS";
export const SKINCARE_TIP_CATEGORIES_FAIL = "SKINCARE_TIP_CATEGORIES_FAIL";

export const SKINCARE_TIP_CONCERNS_REQUEST = "SKINCARE_TIP_CONCERNS_REQUEST";
export const SKINCARE_TIP_CONCERNS_SUCCESS = "SKINCARE_TIP_CONCERNS_SUCCESS";
export const SKINCARE_TIP_CONCERNS_FAIL = "SKINCARE_TIP_CONCERNS_FAIL";
